name: dentcity_management_system
description: "A Dental Management System build for Dr. Reynaldo Tu"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.4.0

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10

  # Database
  drift: ^2.14.0
  sqflite_common_ffi: ^2.3.0
  path_provider: ^2.1.0
  path: ^1.8.0

  # State Management
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5

  # UI
  cupertino_icons: ^1.0.8
  google_fonts: ^8.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Code Generation
  drift_dev: ^2.14.0
  build_runner: ^2.4.0
  riverpod_generator: ^2.4.0

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/